name: portein
channels:
  - conda-forge
dependencies:
  - python>=3.10
  - numpy>=1.24
  - numba>=0.58
  - matplotlib>=3.8
  - pillow>=10.0
  - pyyaml>=6.0
  - typing-extensions>=4.0
  - biotite>=0.40
  - pymol-open-source
  - dssp
  - typer>=0.9
  - pip
  - pip:
      - git+https://github.com/TurtleTools/portein.git
