illustrate_binary: illustrate
convert_binary: convert
center: auto
translation:
- 0.0
- 0.0
- 0.0
scale: 10.0
rotation:
- 0.0
- 0.0
- 0.0
background_color: white
fog_color: white
fog_front_transparency: 1.0
fog_back_transparency: 1.0
sidechain_transparency: 0.8
shadow: true
shadow_cone_angle: 2.0
shadow_cone_difference: 1.0
shadow_cone_fraction: 0.0023
shadow_cone_max: 0.7
padding:
- -2
- -2
contour_outline_min: 3.0
contour_outline_max: 10.0
contour_ikernel: 4
contour_difference_min: 0.0
contour_difference_max: 5.0
subunit_outline_max: 10.0
subunit_outline_min: 3.0
residue_outline_max: 10.0
residue_outline_min: 3.0
carbon_radius: 1.6
sidechain_radius: 1.5
residue_difference: 1.0