background_color: white
carbon_radius: 1.6
center: auto
contour_difference_max: 5.0
contour_difference_min: 0.0
contour_ikernel: 4
contour_outline_max: 10.0
contour_outline_min: 3.0
convert_binary: convert
fog_back_transparency: 1.0
fog_color: white
fog_front_transparency: 1.0
illustrate_binary: illustrate
padding: !!python/tuple
- -2
- -2
residue_difference: 1.0
residue_outline_max: 10.0
residue_outline_min: 3.0
rotation: !!python/tuple
- 0.0
- 0.0
- 0.0
scale: 10.0
shadow: true
shadow_cone_angle: 2.0
shadow_cone_difference: 1.0
shadow_cone_fraction: 0.0023
shadow_cone_max: 0.7
sidechain_radius: 1.5
sidechain_transparency: 0.8
subunit_outline_max: 10.0
subunit_outline_min: 3.0
translation: !!python/tuple
- 0.0
- 0.0
- 0.0
